name = "ecura-landing"
compatibility_date = "2024-01-01"
pages_build_output_dir = "public"
account_id = "8eee3bb064814aa60b770a979332a914"

[[d1_databases]]
binding = "DB"
database_name = "ecura-landing-db"
database_id = "6d0f5ce7-3e31-490d-aa55-f58dcfc96ca1"
migrations_dir = "migrations"
